on:
    push:
      paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']
      tags:
        - "**"
      branches:
        - 'integration'
        - 'release/version*'
        - 'docker-images'
    workflow_dispatch:
jobs:
  call-reusable-workflow:
    uses: nationalsecurityagency/datawave/.github/workflows/microservice-build-image.yaml@add-microservice-workflows
